#!/sbin/busybox sh

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$GPUVOLT$2"'
  eval $evalcmd
else
  evalcmd='eval "GPUVOLT$2=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$GPUVOLT$2"'
  eval $evalcmd
  if [ -f /sys/class/misc/mali_control/voltage_control ];then
    echo "${GPUVOLT1}000 ${GPUVOLT2}000 ${GPUVOLT3}000 ${GPUVOLT4}000 ${GPUVOLT5}000" > /sys/class/misc/mali_control/voltage_control
  fi
fi

