#!/sbin/busybox sh

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$GPUFREQ$2"'
  eval $evalcmd
else
  evalcmd='eval "GPUFREQ$2=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$GPUFREQ$2"'
  eval $evalcmd
  if [ -f /sys/class/misc/mali_control/clock_control ];then
    echo "$GPUFREQ1 $GPUFREQ2 $GPUFREQ3 $GPUFREQ4 $GPUFREQ5" > /sys/class/misc/mali_control/clock_control
  else
    echo $GPUFREQ1 > /sys/module/mali/parameters/step0_clk
    echo $GPUFREQ2 > /sys/module/mali/parameters/step1_clk
    echo $GPUFREQ3 > /sys/module/mali/parameters/step2_clk
    echo $GPUFREQ4 > /sys/module/mali/parameters/step3_clk
    echo $GPUFREQ5 > /sys/module/mali/parameters/step4_clk
  fi
fi

