#!/sbin/busybox sh

if [ "a$3" == "a" ];then
  # echo only
  evalcmd='eval "echo \$GPUSTAYCOUNT$2"'
  eval $evalcmd
else
  # set the value
  evalcmd='eval "GPUSTAYCOUNT$2=$3"'
  eval $evalcmd
  # echo back
  evalcmd='eval "echo \$GPUSTAYCOUNT$2"'
  eval $evalcmd
  if [ -f /sys/class/misc/mali_control/staycount_control ];then
    echo "$GPUSTAYCOUNT1 $GPUSTAYCOUNT2 $GPUSTAYCOUNT3 $GPUSTAYCOUNT4 $GPUSTAYCOUNT5" > /sys/class/misc/mali_control/staycount_control
  fi
fi
