#!/sbin/busybox sh

if [ "a$2" == "a" ];then
  evalcmd='eval "echo \$zram_size"'
  eval $evalcmd
else
  evalcmd='eval "zram_size=$2"'
  eval $evalcmd
  evalcmd='eval "echo \$zram_size"'
  eval $evalcmd

  swapoff /dev/block/zram0 > /dev/null 2>&1
  echo 1 > /sys/devices/virtual/block/zram0/reset
  echo `expr $zram_size \* 1024 \* 1024` > /sys/devices/virtual/block/zram0/disksize
  mkswap /dev/block/zram0 > /dev/null 2>&1
  swapon /dev/block/zram0 > /dev/null 2>&1
  sysctl -w vm.swappiness=90
fi


