#!/sbin/busybox sh
if [ "$SUBSYSTEM" == "block" ];
then
  mountdir="/mnt/ntfs"
  devbase=`basename ${DEVPATH}`
  if [ "$ACTION" == "add" ] && [ ${devbase:0:2} == "sd" ];
  then
    mkdir -p ${mountdir}/${devbase}
    mount -t ntfs /dev/block/${devbase} ${mountdir}/${devbase} || rmdir ${mountdir}/${devbase}
  fi
  if [ "$ACTION" == "remove" ];
  then
    umount -f ${mountdir}/${devbase}
    rmdir ${mountdir}/${devbase}
  fi
fi
