#!/sbin/busybox sh
cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys
tar xvf /res/misc/dev.tar

if grep -q bootmode=2 /proc/cmdline ; then
  cp -a /res/misc/init.40/* /
  echo 0 > /proc/sys/kernel/rom_feature_set
  cp -a /recovery.rc /init.rc
  exec /sbin/init2
fi
if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  echo 0 > /proc/sys/kernel/rom_feature_set
  cp -a /res/misc/init.40/* /
  cp lpm.rc init.rc
  rm init.smdk4210.rc
  exec /sbin/init2
fi

SECONDROM=1
NOBOOTLOGO=0
mkdir /mnt
chmod 755 /mnt
mount -t vfat /dev/block/mmcblk1p1 /mnt && ( touch /mnt/clockworkmod/.nomedia; umount /mnt; )
mount -t ext4 -o ro /dev/block/mmcblk0p12 /preload
mount -t vfat /dev/block/mmcblk0p11 /mnt && ( touch /mnt/clockworkmod/.nomedia )
[ -f /preload/build.prop ] || SECONDROM=0
[ -f /mnt/.secondrom/data.img ] || SECONDROM=0
[ -f /mnt/.secondrom/cache.img ] || SECONDROM=0
[ -f /mnt/.nobootlogo ] && NOBOOTLOGO=1
umount /preload
umount /mnt

if [[ "$NOBOOTLOGO" == "1" && "$SECONDROM" == "0" ]];then
  /sbin/choose_rom
else
  /sbin/choose_rom $SECONDROM
fi

if [ "$?" == "1" ]; then
  SECONDROM=1
else
  SECONDROM=0
fi

/sbin/busybox mount -t ext4 /res/dev/system /system

if [ -f /system/recovery.cpio.gz ];
then
mount -o remount,rw /
zcat /system/recovery.cpio.gz | cpio -idmu
fi;

AOSP=0
MIUI=0
B2G=0
CM10=0
JB=0

[ -d /system/b2g ] && B2G=1
[ -f /system/framework/framework2.jar ] || AOSP=1
[ -f /system/framework/framework-miui.jar ] && MIUI=1
[ -f /system/lib/ssl/engines/libkeystore.so ] && JB=1
[ -f /system/framework/seccamera.jar ] || CM10=1

if [ "$JB" == 1 ];
then
  mv -f /sbin/adbd.jb /sbin/adbd
  if [ "$CM10" == 1 ];
  then
    echo 1 > /proc/sys/kernel/rom_feature_set
rm -rf /vendor
    mv -f /res/misc/init.cm10/* /
  else
    echo 0 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.41/* /
  fi
else
  if [ "$B2G" == 1 ];
  then
    cp -a /res/misc/init.b2g/* /
  fi;

  if [ "$AOSP" == "1" ];
  then
    echo 1 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.cm9/* /
    rm -rf /vendor
  else
    echo 0 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.40/* /
  fi;

  if [ "$MIUI" == 1 ];
  then
    cp -a /res/misc/init.miui/* /
  fi
fi

if [ "$SECONDROM" == "1" ];then
  mv /init.smdk4210.rc.2 /init.smdk4210.rc
  mv /init.rc.2 /init.rc
else
  rm -f /init.rc.2 /init.smdk4210.rc.2
fi

umount /system
rm -rf /res/misc/init*
chmod 755 /innt
chmod 644 /*.rc
chmod 644 /*.prop
exec /sbin/init2
