#!/sbin/busybox sh
cd /
mkdir /dev/block
mknod /dev/block/mmcblk0p9 b 259 1
/sbin/busybox mount -t ext4 /dev/block/mmcblk0p9 /system

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

if [ -f /system/recovery.cpio.gz ];
then
mount -o remount,rw /
zcat /system/recovery.cpio.gz | cpio -idmu
fi;

AOSP=0
MIUI=0

[ -f /system/framework/framework2.jar ] || AOSP=1
[ "`/sbin/busybox grep Slim /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i aosp /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i hydrog /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i =aokp /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i CyanogenMod /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i AdyScorpius /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i cMIUI /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i insanity /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i Oxygen /system/build.prop`" ] && AOSP=1
[ "`/sbin/busybox grep -i =MIUI /system/build.prop`" ] && MIUI=1
[ -f /system/framework/framework-miui.jar ] && MIUI=1

if [ "$AOSP" == 1 ];
then
echo 1 > /proc/sys/kernel/rom_feature_set
/sbin/busybox umount /system
exec /sbin/init.cm
fi;

if [ "$MIUI" == 1 ];
then
mv /init.miui /init.rc
fi

rm -f /init.miui
echo 0 > /proc/sys/kernel/rom_feature_set
busybox umount /system
exec /sbin/init.samsung
