#!/sbin/ext/busybox sh

/sbin/ext/busybox mount -t rootfs -o remount,rw rootfs
/sbin/ext/busybox insmod /lib/modules/logger.ko
/sbin/ext/busybox ln -s /sbin/recovery /sbin/busybox

/sbin/ext/busybox ln -s /sbin/busybox /sbin/sh

/sbin/ext/busybox rm /emmc
/sbin/ext/busybox mkdir /emmc
/sbin/ext/busybox chmod 777 /emmc

/sbin/ext/busybox rm /sdcard
/sbin/ext/busybox mkdir /sdcard
/sbin/ext/busybox chmod 777 /sdcard

/sbin/ext/busybox rm /etc
/sbin/ext/busybox mkdir /etc
/sbin/ext/busybox cat /res/etc/recovery.fstab > /etc/recovery.fstab

#start adbd
stop tvout

/sbin/ext/busybox rm /cache
/sbin/ext/busybox mkdir /cache
/sbin/ext/busybox chmod 777 /cache
/sbin/ext/busybox mount -t ext4 /dev/block/mmcblk0p7 /cache

#cd /
#eval $(/sbin/read_boot_headers /dev/block/mmcblk0p5)
#dd bs=512 if=/dev/block/mmcblk0p5 skip=$recovery_offset count=$recovery_len | busybox xzcat | busybox cpio -i

if /sbin/ext/busybox [ -f /cache/recovery/command ];
then
  /sbin/ext/busybox cp /res/keys-samsung /res/keys
  recovery-samsung
else
  echo 1 > /sbin/recovery-is-running
  recovery
fi;
